### ISSUE TITLE
Feature: Capability to add remote metastore thrift endpoint

### ISSUE THREAD

**Issue by pradeepbhadani** [ExpediaInc/apiary-federation#41]
The current code expects VPCE Service ID for remote metastore but in some cases, we will have direct thrift endpoint of remote metastore and would like to pass that as a parameter to generate WaggleDance config.
This can be achieved(as a workaround) by adding entries for `local_metatores` variables, but the name won't signify remote metastore.

**Acceptance Criteria:**
Add a new variable `remote_metastores_endpoint` to pass thrift endpoints of federated metastores when available.

**Comment by mroark1m** [comment]
I guess this revolves around the context of the word 'local'. It's local in the sense that your endpoint is local, isn't it, otherwise the workaround would not work? It's remote in the sense that it's a proxy or something and the 'actual' metastore is not in your account.

I liked your suggestion in the chat about changing it to metastore_endpoint and remove the 'local' word which causes the concern, but that's a breaking change at this point, not sure I like that just to fix naming for a workaround... we'd probably also want to change remote_metastores to remote_metastore_vpc_endpoints or something for consistency...

Another option to me is just to change the description of the variable so that it's clear that it's only the 'endpoint' which has to be local.... for example, change:

 description = "List of federated Metastores in current account."

to

 description = "List of federated Metastore **endpoints** directly accessible on the local network."

in the end, this federation concept is not about where the metastore actually lives after all, that's implementation dependent, and the code we have already works for both cases.

**Comment by pradeepbhadani** [comment]
@mroark1m  - Yes, updating variable name would break the caller side if it uses the new module version but it will not break the existing module version.

I like your idea to make the description more clear at this stage to avoid name change. I will raise PR for this.
